[package]
name = "leema"
version = "0.0.1"
authors = ["Matthew Graham <mdg149@gmail.com>"]
rustc-link-search = ["."]
rustc-link-lib = ["leemalex"]

[[bin]]
name = "leema"

[[bin]]
name = "leemaw"

[dependencies]
futures = "0.1"
libc = "0.2"
docopt = "0.6"
hyper = "0.10"
rand = "0.3"
rustc-serialize = "0.3"
tokio-core = "0.1"
