
binop_separator = "Front"
blank_lines_upper_bound = 3
brace_style = "AlwaysNextLine"
force_multiline_blocks = true
imports_indent = "Block"
indent_style = "Block"
match_arm_blocks = true
max_width = 80
merge_derives = false
newline_style = "Unix"
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true

ignore = [
    "src/leema/parse.rs",
    "src/leema/parse.rs",
    "parse.rs",
    "src/leema/parse",
]
